{% set name = "isbnlib" %}
{% set version = "3.10.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/isbnlib-{{ version }}.tar.gz
  sha256: 96f90864c77b01f55fa11e5bfca9fd909501d9842f3bc710d4eab85195d90539

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
  run:
    - python >=3.8
    - twine >=4.0.1

test:
  imports:
    - isbnlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xlcnd/isbnlib
  summary: Extract, clean, transform, hyphenate and metadata for ISBNs (International Standard Book Number).
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE-LGPL-3.0.txt

extra:
  recipe-maintainers:
    - maxb2
